# Generated by Django 2.0.7 on 2018-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameName', models.CharField(max_length=600)),
                ('GameDiscryp', models.TextField()),
                ('GameLink', models.CharField(max_length=600)),
                ('ImageGame', models.ImageField(max_length=600, upload_to='')),
            ],
        ),
    ]
