# Generated by Django 2.0.7 on 2018-07-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_auto_20180711_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='ImageGame',
        ),
    ]
