# Generated by Django 2.0.7 on 2018-07-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0003_remove_gamemodel_imagegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='GameImage',
            field=models.CharField(default='dsada', max_length=600),
            preserve_default=False,
        ),
    ]
